development:
  :address: smtp.live.com
  :port: 587
  :authentication: plain
  :user_name: homeworktracker@live.com
  :password: K1pUEtXxvzKG6x9
  :enable_starttls_auto: true
production:
  :address: smtp.live.com
  :port: 587
  :authentication: plain
  :user_name: homeworktracker@live.com
  :password: K1pUEtXxvzKG6x9
  :enable_starttls_auto: true